# visit https://github.com/mojombo/jekyll/wiki/Configuration for more settings

paginate: 10 # pagination based on number of posts
paginate_path: "page:num"
exclude: ["README.md"] # files to exclude
highlighter: pygments
markdown: kramdown


defaults:
  -
    scope:
      path: "" # empty string for all files
    values:
      title: Yoyo

description: Stylish Jekyll Theme
author:
  name: Yoyo
  email: ttvu90@gmail.com
  github: https://github.com/tranthanhvu
  twitter: ThanhVu_
  pinterest: 
  linkedin: https://vn.linkedin.com/pub/vũ-trần/56/40b/402
  bio: 03/08/1990
  email_md5: b888a728f505d99b70b3d48f46d26994

rss_path: feed.xml
categories_path: categories.html
tags_path: tags.html

BASE_PATH:
